"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,Workflow,Plus,Zap,Play,Power,Clock,Radio} from "lucide-react";
type W={id:string;name:string;description:string|null;trigger_type:string;enabled:boolean;config:any;next_run_at:string|null};
export default function AutomationPage(){const [items,setItems]=useState<W[]>([]),[name,setName]=useState(""),[description,setDescription]=useState(""),[trigger,setTrigger]=useState("manual"),[cron,setCron]=useState("*/5 * * * *"),[timezone,setTimezone]=useState("UTC"),[eventName,setEventName]=useState(""),[saving,setSaving]=useState(false),[running,setRunning]=useState(""),[error,setError]=useState(""),[output,setOutput]=useState("");
useEffect(()=>{fetch("/api/automation").then(r=>r.json()).then(d=>{if(d.workflows)setItems(d.workflows);else setError(d.error||"Unable to load workflows.")})},[]);
async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");const r=await fetch("/api/automation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description,instruction:description,trigger_type:trigger,cron,timezone,event_name:eventName})});const d=await r.json();if(!r.ok)setError(d.error||"Failed.");else{setItems(x=>[d.workflow,...x]);setName("");setDescription("");setEventName("")}setSaving(false)}
async function execute(id:string){setRunning(id);setError("");setOutput("");const r=await fetch("/api/automation/execute",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)setError(d.error||"Execution failed.");else setOutput(d.run?.output||"Workflow completed.");setRunning("")}
async function toggle(w:W){const r=await fetch("/api/automation",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:w.id,enabled:!w.enabled})});const d=await r.json();if(r.ok)setItems(x=>x.map(i=>i.id===w.id?{...i,enabled:d.workflow.enabled}:i));else setError(d.error||"Failed to update workflow.")}
return <main className="ai-page"><header className="ai-head"><div><small>AUTOMATION ENGINE</small><h1>Schedule. Trigger. Execute.</h1><p>Run workflows automatically on a cron schedule or when an event arrives.</p></div><a href="/dashboard"><ArrowLeft size={16}/> Dashboard</a></header><section className="ai-box"><form onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Workflow name" maxLength={160} required/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe exactly what this workflow should do." maxLength={4000} required/><select value={trigger} onChange={e=>setTrigger(e.target.value)}><option value="manual">Manual trigger</option><option value="schedule">Schedule trigger</option><option value="event">Event trigger</option></select>{trigger==="schedule"&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input value={cron} onChange={e=>setCron(e.target.value)} placeholder="*/5 * * * *"/><input value={timezone} onChange={e=>setTimezone(e.target.value)} placeholder="UTC / Asia/Kolkata"/></div>}{trigger==="event"&&<input value={eventName} onChange={e=>setEventName(e.target.value)} placeholder="Event name, e.g. deployment.completed"/>}<button disabled={saving}><Plus size={17}/>{saving?"Creating…":"Create Workflow"}</button></form>{error&&<p className="ai-error">{error}</p>}{output&&<div className="ai-output"><small>LAST EXECUTION</small><pre>{output}</pre></div>}</section><section className="module-grid">{items.map(w=><article key={w.id}><div className="icon">{w.trigger_type==="schedule"?<Clock size={22}/>:w.trigger_type==="event"?<Radio size={22}/>:<Workflow size={22}/>}</div><h3>{w.name}</h3><p>{w.description||"No description."}</p><small><Zap size={13}/> {w.trigger_type.toUpperCase()} · {w.enabled?"ENABLED":"DISABLED"}</small>{w.trigger_type==="schedule"&&<small style={{display:"block",marginTop:7}}>Next: {w.next_run_at?new Date(w.next_run_at).toLocaleString():"Not scheduled"}</small>}{w.trigger_type==="event"&&<small style={{display:"block",marginTop:7}}>Event: {w.config?.event_name||"—"}</small>}<div style={{display:"flex",gap:8,marginTop:16}}><button onClick={()=>execute(w.id)} disabled={!w.enabled||running===w.id}><Play size={14}/>{running===w.id?"Running…":"Run Now"}</button><button onClick={()=>toggle(w)}><Power size={14}/>{w.enabled?"Disable":"Enable"}</button></div></article>)}</section></main>}