"use client";
import {useState} from "react";
import {Sparkles,ShieldCheck,Zap,Globe,ArrowRight,Command,ScanLine,Workflow} from "lucide-react";
const features=[["AI Innovation Engine","Turn ideas into plans, products, code and experiments.",Sparkles],["Security Core","Rate limits, validation and a security-first architecture.",ShieldCheck],["Automation Lab","Design repeatable workflows for everyday work.",Workflow],["Global Tools","QR, barcode, generators and utility modules in one workspace.",ScanLine],["Mission Mode","Convert ambitious goals into clear missions and milestones.",Zap],["Multi-language","Build experiences for a global audience from one core.",Globe]];
function Brand(){return <div className="brand"><span className="brand-mark"><i/><b>G</b></span><strong>GOD-OF</strong><small>INNOVATION</small></div>}
export default function Home(){
 const [idea,setIdea]=useState("");const [out,setOut]=useState("");const [loading,setLoading]=useState(false);
 async function launch(){const v=idea.trim();if(!v){setOut("Enter an idea to initialize your first mission.");return}setLoading(true);setOut("");try{const r=await fetch("/api/missions/auto-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea:v})});const d=await r.json();if(r.status===401){setOut("Sign in to launch an AI-powered mission.");return}if(!r.ok){setOut(d.error||"Launch failed.");return}setOut("Mission created: "+d.mission.title);setIdea("");window.location.href="/missions/"+d.mission.id}catch{setOut("Launch failed. Please try again.")}finally{setLoading(false)}}
 return <main><nav><Brand/><div className="status"><i/> CORE ONLINE</div></nav><section className="hero"><div className="badge">INNOVATION COMMAND CENTER</div><h1>BUILD WHAT<br/><em>DOESN'T EXIST.</em></h1><p>One futuristic workspace for ideas, AI, automation, tools, missions and execution.</p><div className="launch"><Command size={20}/><input value={idea} onChange={e=>setIdea(e.target.value)} onKeyDown={e=>e.key==="Enter"&&launch()} placeholder="Describe what you want to build..." /><button onClick={launch} disabled={loading}>{loading?"Planning…":"Launch"} {!loading&&<ArrowRight size={18}/>}</button></div>{out&&<div className="result">{out} {out.startsWith("Sign in")&&<a href="/login">Open login →</a>}</div>}</section><section className="grid">{features.map(([title,desc,Icon])=><article key={title as string}><div className="icon"><Icon size={22}/></div><h3>{title as string}</h3><p>{desc as string}</p><a href={title==="Mission Mode"?"/missions":title==="AI Innovation Engine"?"/ai":title==="Automation Lab"?"/automation":"/dashboard"}>Open module <ArrowRight size={15}/></a></article>)}</section><footer><span>GOD-OF INNOVATION · FOUNDATION v0.2</span><span>AI → MISSION → AUTOMATION → EXECUTION</span></footer></main>
}