"use client";
import {useEffect,useState} from "react";
import {LayoutDashboard,Sparkles,Target,Workflow,ShieldCheck,Settings,ArrowUpRight,PlayCircle,GitBranch} from "lucide-react";
type Mission={id:string;title:string;status:string};
type W={id:string;name:string;enabled:boolean;trigger_type:string};
export default function Dashboard(){
 const [active,setActive]=useState("Overview");const [idea,setIdea]=useState("");const [launching,setLaunching]=useState(false);const [message,setMessage]=useState("");const [missions,setMissions]=useState<Mission[]>([]);const [workflows,setWorkflows]=useState<W[]>([]);
 useEffect(()=>{fetch("/api/missions").then(r=>r.json()).then(d=>setMissions(d.missions||[])).catch(()=>{});fetch("/api/automation").then(r=>r.json()).then(d=>setWorkflows(d.workflows||[])).catch(()=>{})},[]);
 async function launch(){const v=idea.trim();if(!v){setMessage("Enter an idea first.");return}setLaunching(true);setMessage("");try{const r=await fetch("/api/missions/auto-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea:v})});const d=await r.json();if(!r.ok){setMessage(d.error||"AI launch failed.");return}setIdea("");setMessage("Mission created. Opening execution workspace…");window.location.href="/missions/"+d.mission.id}catch{setMessage("AI launch failed. Please try again.")}finally{setLaunching(false)}}
 const cards=[["AI Innovation","Generate ideas, plans and implementation paths.",Sparkles,"/ai"],["Missions",missions.length+" missions in your workspace.",Target,"/missions"],["Automation",workflows.length+" workflows configured.",Workflow,"/automation"],["Security","Review platform protection and activity.",ShieldCheck,"#"]];
 return <main className="dash"><aside><div className="brand"><span className="brand-mark"><i/><b>G</b></span><strong>GOD-OF</strong><small>INNOVATION</small></div><nav>{[["Overview",LayoutDashboard],["AI Engine",Sparkles],["Missions",Target],["Automation",Workflow],["Security",ShieldCheck],["Settings",Settings]].map(([name,Icon])=><button className={active===name?"active":""} onClick={()=>setActive(name as string)} key={name as string}><Icon size={18}/>{name as string}</button>)}</nav></aside><section className="panel"><header><div><small>COMMAND CENTER</small><h1>{active}</h1></div><div className="online"><i/> SYSTEM ONLINE</div></header><div className="welcome"><small>CONNECTED EXECUTION PIPELINE</small><h2>Idea → AI → Mission → Automation</h2><p>Start from one idea, generate an execution plan, track tasks and connect repeatable workflows.</p><div className="dash-launch"><input value={idea} onChange={e=>setIdea(e.target.value)} onKeyDown={e=>e.key==="Enter"&&launch()} placeholder="What do you want to build?" /><button onClick={launch} disabled={launching}><PlayCircle size={16}/>{launching?"Planning…":"Launch AI Mission"}</button></div>{message&&<div className="dash-message">{message}</div>}</div><div className="pipeline"><div><Sparkles size={18}/><b>AI</b><span>Plan</span></div><GitBranch size={16}/><div><Target size={18}/><b>Mission</b><span>Execute</span></div><GitBranch size={16}/><div><Workflow size={18}/><b>Automation</b><span>Repeat</span></div></div><div className="module-grid">{cards.map(([title,desc,Icon,href])=><article key={title as string}><div className="icon"><Icon size={22}/></div><h3>{title as string}</h3><p>{desc as string}</p><a href={href as string}>Open module <ArrowUpRight size={15}/></a></article>)}</div></section></main>
}